services:
  app-sr-admin:
    build: .
    container_name: smartranking-admin
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017
    volumes:
      - .:/home/node/micro-admin-backend
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

