### Variables
@urlLocal = http://localhost:8080/api/v1/challenges
@contentType = application/json

### POST Challenge 1
POST {{urlLocal}}
Content-Type: {{contentType}}

{
    "challengeDate": "2024-10-20 16:00:00.000",
    "requester": "66ffe868fb57706847fdb2bb",
    "players": ["66ffe868fb57706847fdb2bb","66ffe853fb57706847fdb2b8"]
}


### GET all
GET {{urlLocal}}


### GET all from a player
# @prompt idPlayer
GET {{urlLocal}}?idPlayer={{idPlayer}}

### GET all from a category
# @prompt idCategory
GET {{urlLocal}}?idCategory={{idCategory}}


### PUT
# @prompt challenge
PUT {{urlLocal}}/{{challenge}}
Content-Type: {{contentType}}

{
    "challengeDate": "2024-09-20 17:00:00.000",
    "status": "ACCEPTED"
}

### DELETE
# @prompt challenge
DELETE {{urlLocal}}/{{challenge}}


### POST set a game
# @prompt challenge
POST {{urlLocal}}/{{challenge}}/game
Content-Type: {{contentType}}

{
    "def": "66ffe853fb57706847fdb2b8",
    "result": [
        {
            "set": "6-3"
        },
        {
            "set": "6-2"
        }
    ]
}
