### Variables
@urlLocal = http://localhost:8080/api/v1/players
@contentType = application/json

### POST
# @name player
POST {{urlLocal}}
Content-Type: {{contentType}}

{
    "phone": "84 9999-5958",
    "email": "eng.mykael@gmail.com",
    "name": "Mykael Mello"
}

### GET all
GET {{urlLocal}}


### GET one
# @prompt playerId
# @name player
GET {{urlLocal}}/{{playerId}}

### GET one
GET {{urlLocal}}/{{player.response.body._id}}

### PUT
PUT {{urlLocal}}/{{player.response.body._id}}
Content-Type: {{contentType}}

{
    "phone": "84 99666-5656",
    "email": "roger_guedes@provider.com",
    "name": "Roger Guedes"
}

### DELETE
DELETE {{urlLocal}}/{{player.response.body._id}}

### UPLOAD PHOTO
# @prompt playerId
POST {{urlLocal}}/{{playerId}}/upload
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="file"; filename="imageNest.png"
Content-Type: image/png

< ./api-gateway/imageNest.png
--MfnBoundry--
